import type { fanCafes } from '@/lib/db/schema'

type FanCafeRecord = typeof fanCafes.$inferSelect

export const previewFanCafes: FanCafeRecord[] = [
  {
    id: 1,
    name: 'Twisted Wonderland CSE: A Nightmare Before Christmas',
    fandom: 'Twisted Wonderland',
    location: 'Spillstone Coffee, Jalan Pudu',
    startDate: '2026-10-31',
    endDate: null,
    instagram: null,
    instagramPostUrl: 'https://www.instagram.com/p/DbfJPaIxT_1/',
    startTime: '12:00 PM',
    endTime: '5:00 PM',
    description: null,
    createdAt: new Date(0),
  },
  {
    id: 2,
    name: 'Alien Stage CSE: The Grand Birthday Banquet',
    fandom: 'Alien Stage',
    location: 'Doutor Coffee, LaLaport BBCC',
    startDate: '2026-11-22',
    endDate: null,
    instagram: null,
    instagramPostUrl: 'https://www.instagram.com/p/DdgiZpEJsSo/',
    startTime: '11:00 AM',
    endTime: '5:00 PM',
    description: null,
    createdAt: new Date(0),
  },
  {
    id: 3,
    name: "Batman: The Wayne Family's Galaween",
    fandom: 'Batman',
    location: 'MM Cafe, LaLaport BBCC',
    startDate: '2026-10-17',
    endDate: null,
    instagram: null,
    instagramPostUrl: 'https://www.instagram.com/p/DdtwtsfzAdZ/',
    startTime: '11:00 AM',
    endTime: '4:00 PM',
    description: null,
    createdAt: new Date(0),
  },
  {
    id: 4,
    name: 'IDOLiSH7: HAPPY iN THE CUP!!',
    fandom: 'IDOLiSH7',
    location: 'MM Cafe, LaLaport BBCC',
    startDate: '2026-10-18',
    endDate: null,
    instagram: null,
    instagramPostUrl: 'https://www.instagram.com/p/Dc8QsUdgYFX/',
    startTime: '12:00 PM',
    endTime: '6:00 PM',
    description: null,
    createdAt: new Date(0),
  },
]
